language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: uXK06wJ0FMo1hpWfXI5KyXakad/lHeLPSTCAH3J/WQAQoxqZ3bw/sht1gvgtckT45uMTjfc4May1n2gabm8bf22n8db2gToEF26kC5ZV2cBBxpRB6E2D6LhUcz303au9uciYvMzTWGYX8R9RhPPw0lkrGR56lqPaAAVuVALWNit5ntsdsgXnuuiSEyjFU4BfN7DaXx+vkpcbVzksbZLEEBwD3ubprrEJBTaCAStGuTSO8Eqkp8SYe6SY5qD3+hIHksgkNQK38gG6eEbhh2Go+LDqTsOF1HPew5gk8kVXBxb6E4x+PCW3k3PRt3HGk2Ay6D7J8c77BRmCEu7V6KtYrwks2nCAafzlinkk3o73NyQGsH4nDPGLTAPhKw9Dagdho1mkhaeN1z0I6Jj4Pyg0Y38zplfsUkqizCNDcLjk65zgdwbx+/9J4C4TFxvDfzL1X76u5t65OD+JW617VOa16Soppv6QVphGL3dwOXhpk/6P3MsZhnh+Vdjacbdi04fj9yJWsZIilhgAxQBNaCczmEBgdnirm1QeAm/CrvlLy5ACumLbteQvFOLTXAsIyzmz6PxFc17cwsWlbyrf2HEyr/xRGbBsKh/xmCrCAqRpC5GVVTLQXmUkCCZwAYqdKCfFLoPeo2/XLIRhI9F6WqErVvstF4Ma476oEa5wub/JZUw=
